version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic_user
      MYSQL_PASSWORD: petclinic_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-petclinic
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic_user
      SPRING_DATASOURCE_PASSWORD: petclinic_pass
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs

volumes:
  mysql_data:
